#!/bin/sh
#
# Load modules related to TS-4100
#

umask 077

start() {
	printf "Loading modules for TS-4100 peripherals: "
	modprobe wilc_spi
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
