#!/bin/sh
#
# Print build information on startup
#

umask 077


start() {
	echo ""
	echo "============== Build Information =============="
	echo "Buildroot Hash: $(cat /etc/buildroot_hash)"
	echo "Buildroot defconfig: $(cat /etc/buildroot_defconfig)"
	echo "Build Time: $(cat /etc/build_time)"
	echo "==============================================="
	echo ""
}

stop() {
	true
}

restart() {
	stop
	start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
