################################################################################
#
# nxp-bt-wifi-firmware-ets
#
################################################################################

NXP_BT_WIFI_FIRMWARE_ETS_VERSION = lf-6.12.34_2.1.0
NXP_BT_WIFI_FIRMWARE_ETS_SITE = $(call github,nxp-imx,imx-firmware,$(NXP_BT_WIFI_FIRMWARE_ETS_VERSION))
NXP_BT_WIFI_FIRMWARE_ETS_LICENSE = NXP Software License Agreement
NXP_BT_WIFI_FIRMWARE_ETS_LICENSE_FILES = LICENSE.txt
NXP_BT_WIFI_FIRMWARE_ETS_REDISTRIBUTE = NO

NXP_BT_WIFI_FIRMWARE_ETS_FILES_$(BR2_PACKAGE_NXP_BT_WIFI_FIRMWARE_ETS_8801) += FwImage_8801_SD
NXP_BT_WIFI_FIRMWARE_ETS_FILES_$(BR2_PACKAGE_NXP_BT_WIFI_FIRMWARE_ETS_8987) += FwImage_8987
NXP_BT_WIFI_FIRMWARE_ETS_FILES_$(BR2_PACKAGE_NXP_BT_WIFI_FIRMWARE_ETS_8997_SD) += FwImage_8997_SD
NXP_BT_WIFI_FIRMWARE_ETS_FILES_$(BR2_PACKAGE_NXP_BT_WIFI_FIRMWARE_ETS_8997_PCIE) += FwImage_8997
NXP_BT_WIFI_FIRMWARE_ETS_FILES_$(BR2_PACKAGE_NXP_BT_WIFI_FIRMWARE_ETS_9098_SD) += FwImage_9098_SD
NXP_BT_WIFI_FIRMWARE_ETS_FILES_$(BR2_PACKAGE_NXP_BT_WIFI_FIRMWARE_ETS_9098_PCIE) += FwImage_9098_PCIE
NXP_BT_WIFI_FIRMWARE_ETS_FILES_$(BR2_PACKAGE_NXP_BT_WIFI_FIRMWARE_ETS_IW416) += FwImage_IW416_SD
NXP_BT_WIFI_FIRMWARE_ETS_FILES_$(BR2_PACKAGE_NXP_BT_WIFI_FIRMWARE_ETS_IW610) += FwImage_IW610_SD
NXP_BT_WIFI_FIRMWARE_ETS_FILES_$(BR2_PACKAGE_NXP_BT_WIFI_FIRMWARE_ETS_IW612) += FwImage_IW612_SD

define NXP_BT_WIFI_FIRMWARE_ETS_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0644 -D $(@D)/nxp/wifi_mod_para.conf \
		$(TARGET_DIR)/lib/firmware/nxp/wifi_mod_para.conf
	$(INSTALL) -m 0644 -D $(@D)/nxp/mfguart/helper_uart_3000000.bin \
		$(TARGET_DIR)/lib/firmware/nxp/helper_uart_3000000.bin
	$(foreach f,$(NXP_BT_WIFI_FIRMWARE_ETS_FILES_y), \
		$(INSTALL) -m 0644 -D $(@D)/nxp/$(f)/* $(TARGET_DIR)/lib/firmware/nxp/
	)
endef

$(eval $(generic-package))
