#!/bin/sh

case "$1" in
        start|"")
		/bin/weston-run.sh &
		exit 0
                ;;
        stop)
		killall weston
                exit 0
                ;;
        *)
                echo "Usage: $0 {start|stop}" >&2
                exit 1
                ;;
esac
