#!/bin/sh
#
# Load modules related to TS-7553-V2
#

umask 077

start() {
	printf "Loading modules for TS-7553-V2 peripherals: "
	modprobe ts-st7565p-fb
	modprobe gpio_keys
	modprobe matrix_keypad
	modprobe wilc_spi
	modprobe inv_mpu6050_i2c
	modprobe ak8975
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
